service: youtube-data-scraper

plugins:
  - serverless-plugin-typescript

package:
  include:
    - src/handlers/scrape-videos/search_filter

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  environment:
    GOOGLE_API_KEY: ${env:GOOGLE_API_KEY}
    SCRAPE_VIDEOS_REQUEST_QUEUE_URL: !Ref ScrapeVideosRequestQueue

  iamRoleStatements:
  - Effect: Allow
    Action:
      - sqs:SendMessage
      - sqs:SendMessageBatch
    Resource: 
    - !Join
        - ':'
        - - 'arn:aws:sqs'
          - !Ref AWS::Region
          - !Ref AWS::AccountId
          - ${self:service}-scrape-videos-request

functions:
  scrape-playlist-ids:
    handler: src/handlers/api/scrape-playlist-ids/index.handler
    events:
      - http:
          path: scrape
          method: get
          request:
            parameters:
              querystrings:
                channel: true

  scrape-videos:
    handler: src/handlers/scrape-videos/index.handler
    events:
      - sqs:
          arn: !GetAtt ScrapeVideosRequestQueue.Arn
          batchSize: 1

resources:
  - ${file(resources/sqs.yml)}
  - ${file(resources/apigateway.yml)}
  - ${file(resources/rds.yml)}
