Resources:
  ParameterRequestValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: ParameterRequestValidator
        RestApiId:
          Ref: ApiGatewayRestApi # reference the APIGateway RestAPI
        ValidateRequestBody: false
        ValidateRequestParameters: true #enforce request param validation

  ApiGatewayMethodScrapeGet:
    Properties:
      RequestValidatorId:
        Ref: ParameterRequestValidator

  ApiGatewayMethodVideoIdVarGet:
    Properties:
      RequestValidatorId:
        Ref: ParameterRequestValidator

  ApiGatewayMethodVideoIdVarDelete:
    Properties:
      RequestValidatorId:
        Ref: ParameterRequestValidator