Resources:
  YoutubeDataScraperRDSCluster:
    Type: 'AWS::RDS::DBCluster'
    Properties:
      MasterUsername: ${env:RDS_USERNAME}
      MasterUserPassword: ${env:RDS_PASSWORD}
      DBClusterIdentifier: ${self:service}-serverless-rds-cluster
      Engine: aurora-mysql
      DatabaseName: mydb
  YoutubeDataScraperRDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: ${self:service}-serverless-rds-instance
      Engine: aurora-mysql
      DBClusterIdentifier: !Ref YoutubeDataScraperRDSCluster
      PubliclyAccessible: 'true'
      DBInstanceClass: db.t3.small